---
title: "Final Project"
subtitle: "Data Science for Public Policy"
author: "Madeleine Adelson, Stephanie Jamilla, Jamie Jelly Murtha"
format: 
  html:
    code-line-numbers: true
    body-width: 1600px
embed-resources: true
editor_options: 
  chunk_output_type: console
execute: 
  warning: false
urlcolor: blue
toc: true
---

Loading packages:
```{r}

library(tidyverse)
library(ggplot2)
library(sf)
library(tidycensus)
library(stringr)
library(dplyr)

```

# Exploring the Data

## Cleaning Urban Heat Data
```{r}

# Heat Data - cleaning up columns
dc_heat <- read_sf("data/2024UHI_DC.kml") |>
  separate(Name, c("city","temp"), "- ") |>
  separate(temp, c("uhi", "temp"), "°") |>
  separate(temp, c("temp", "block_group", "x"), ": ") |>
  select(-city, -temp, -x, -Description)

# Changing the UHI variable from character to numeric
dc_heat$uhi <- as.numeric(dc_heat$uhi)
```

## Cleaning DC Land Cover Data
```{r}

landcover <- read_sf("data/Urban_Tree_Canopy_by_Census_Block_Group_in_2020.shp") |>
  rename(block_group = GEOID)
names(landcover) <- names(landcover) |>
  tolower()

```

## Exploring Census Demographic Data

```{r}
# Loading possible variables to use for 2016-2020 ACS
variables <- load_variables(2020, "acs5") |>
  filter(geography == "block group")

```

## Stitching Together Final Dataset
```{r}



```

## Initial EDA
### DC Heat Map
```{r}

dc_heat |>
  ggplot() +
  geom_sf(mapping = aes(fill = uhi)) +
  scale_fill_gradient(
    'Urban Heat Island Index',
    low = '#FCEBA6',
    high = '#AF1F29'
  ) +
  labs(title = "DC Urban Heat Island Intensity") +
  theme_minimal() 

```

# Supervised Machine Learning Applications
## Decision Trees

Deciding the threshold for hot vs. not hot:
```{r}



```

## Linear Regression
```{r}



```

## Random Forests
```{r}



```